### ISSUE TITLE
Would you like to add Food and Resources categories to the default configuration?

### ISSUE THREAD

**Issue by MadeByPP** [5Dev24/Recycle#12]
Water Jug in the Food category, CCTV Camera and Targeting Computer in the Resources category are not added, so it is not the same as the basic recycler. Would you like to add these two categories to the default configuration?

**Comment by 5Dev24** [comment]
This repo lives on my Github b/c I was the previous maintainer. 0x89A now maintains it. If you want this issue to be seen, please post [here](https://umod.org/community/recycle).
